//
// Generated file, do not edit! Created by opp_msgtool 6.0 from veins/modules/application/traci/TraCIDemo11pMessage.msg.
//

#ifndef __VEINS_TRACIDEMO11PMESSAGE_M_H
#define __VEINS_TRACIDEMO11PMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef VEINS_API
#  if defined(VEINS_EXPORT)
#    define VEINS_API  OPP_DLLEXPORT
#  elif defined(VEINS_IMPORT)
#    define VEINS_API  OPP_DLLIMPORT
#  else
#    define VEINS_API
#  endif
#endif


namespace veins {

class TraCIDemo11pMessage;

}  // namespace veins

#include "veins/base/utils/Coord_m.h" // import veins.base.utils.Coord

#include "veins/modules/messages/BaseFrame1609_4_m.h" // import veins.modules.messages.BaseFrame1609_4

#include "veins/base/utils/SimpleAddress_m.h" // import veins.base.utils.SimpleAddress


namespace veins {

/**
 * Class generated from <tt>veins/modules/application/traci/TraCIDemo11pMessage.msg:34</tt> by opp_msgtool.
 * <pre>
 * // This packet extends the base frame and adds our new data fields.
 * packet TraCIDemo11pMessage extends BaseFrame1609_4
 * {
 *     string demoData;
 *     LAddress::L2Type senderAddress = -1;
 *     int serial = 0;
 *     Coord nodeMobilityCoord; // The vehicle's position
 *     bool isBeacon = false;
 *     int hopCount = 0;
 *     double speed;
 *     double direction;
 * }
 * </pre>
 */
class VEINS_API TraCIDemo11pMessage : public ::veins::BaseFrame1609_4
{
  protected:
    ::omnetpp::opp_string demoData;
    LAddress::L2Type senderAddress = -1;
    int serial = 0;
    Coord nodeMobilityCoord;
    bool isBeacon_ = false;
    int hopCount = 0;
    double speed = 0;
    double direction = 0;

  private:
    void copy(const TraCIDemo11pMessage& other);

  protected:
    bool operator==(const TraCIDemo11pMessage&) = delete;

  public:
    TraCIDemo11pMessage(const char *name=nullptr, short kind=0);
    TraCIDemo11pMessage(const TraCIDemo11pMessage& other);
    virtual ~TraCIDemo11pMessage();
    TraCIDemo11pMessage& operator=(const TraCIDemo11pMessage& other);
    virtual TraCIDemo11pMessage *dup() const override {return new TraCIDemo11pMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getDemoData() const;
    virtual void setDemoData(const char * demoData);

    virtual const LAddress::L2Type& getSenderAddress() const;
    virtual LAddress::L2Type& getSenderAddressForUpdate() { return const_cast<LAddress::L2Type&>(const_cast<TraCIDemo11pMessage*>(this)->getSenderAddress());}
    virtual void setSenderAddress(const LAddress::L2Type& senderAddress);

    virtual int getSerial() const;
    virtual void setSerial(int serial);

    virtual const Coord& getNodeMobilityCoord() const;
    virtual Coord& getNodeMobilityCoordForUpdate() { return const_cast<Coord&>(const_cast<TraCIDemo11pMessage*>(this)->getNodeMobilityCoord());}
    virtual void setNodeMobilityCoord(const Coord& nodeMobilityCoord);

    virtual bool isBeacon() const;
    virtual void setIsBeacon(bool isBeacon);

    virtual int getHopCount() const;
    virtual void setHopCount(int hopCount);

    virtual double getSpeed() const;
    virtual void setSpeed(double speed);

    virtual double getDirection() const;
    virtual void setDirection(double direction);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TraCIDemo11pMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TraCIDemo11pMessage& obj) {obj.parsimUnpack(b);}


}  // namespace veins


namespace omnetpp {

template<> inline veins::TraCIDemo11pMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<veins::TraCIDemo11pMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __VEINS_TRACIDEMO11PMESSAGE_M_H

