
[General]
cmdenv-express-mode = true
cmdenv-autoflush = true
cmdenv-status-frequency = 1s
**.cmdenv-log-level = info
cmdenv-redirect-output = true

#cmdenv-express-mode = false
#cmdenv-autoflush = true
#cmdenv-status-frequency = 1s
#**.cmdenv-log-level = trace
#cmdenv-log-prefix = "[%t] [%e] [%m]"
#cmdenv-output-file = result.log

#vehicular-density = ${100, 150, 200}
#fog-density = {2, 5, 8, 10, 12, 15}
#repeat = 2	
#seed-set = ${0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29}
seed-set = ${0}
#cmdenv-output-file=${resultdir}/cmd_results/${configname}-${iterationvarsf}-${seedset}.out
#eventlog-file = ${resultdir}/${configname}-${iterationvarsf}-${repetition}.txt

image-path = /home/nadia/Brock/Thesis/veins-veins-5.2/images
#ned-path=.;/home/nadia/Brock/Thesis/veins-veins-5.2/src/veins;/home/nadia/Brock/Thesis/inet-3.8.3/src/inet;/home/nadia/Brock/Thesis/openflow4core-20240124/src/openflow;
ned-path=.;
network = RSUExampleScenario

##########################################################
#            Simulation parameters                       #
##########################################################
debug-on-errors = false
print-undisposed = true

sim-time-limit = 1000s

**.scalar-recording = false
**.vector-recording = false

**.numControllers = 5
**.spanningTree.startNode = 4
**.highlightActivePorts = true
# This tells every module with a radio to use the same radio medium
*.**.radioMediumModule = "radioMedium"

#WDC
#*.playgroundSizeX = 3088m
#*.playgroundSizeY = 2517m
*.playgroundSizeX = 3500m
*.playgroundSizeY = 3000m
*.playgroundSizeZ = 50m

#BGH
#*.playgroundSizeX = 3478m
#*.playgroundSizeY = 2179m
#*.playgroundSizeZ = 50m

##########################################################
# Annotation parameters                                  #
##########################################################
*.annotations.draw = true

##########################################################
# Obstacle parameters                                    #
##########################################################
*.obstacles.obstacles = xmldoc("config.xml", "//AnalogueModel[@type='SimpleObstacleShadowing']/obstacles")

##########################################################
#            TraCIScenarioManager parameters             #
##########################################################
*.manager.updateInterval = 1s
*.manager.host = "localhost"
*.manager.port = 9999
*.manager.autoShutdown = true

#*.manager.launchConfig = xmldoc("washingtondc.launchd.xml")
#*.manager.launchConfig = xmldoc("/input/washingtondc/seed-" + string(${seed=0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29}) + "/" + string(${Nv=20,30,40,50,60,80,100,120,200}) + "/washingtondc.launchd.xml")
*.manager.launchConfig = xmldoc("./input/washingtondc/seed-" + string(${seedset}) + "/" + string(${Nv=20}) + "/washingtondc.launchd.xml")
**.manager.sumoExtraOptions = "--error-log /tmp/sumo_seed${runnumber}.err --log /tmp/sumo_seed${runnumber}.log --verbose true"

#*.manager.launchConfig = xmldoc("washingtondc"+string(${seedset})+".launchd.xml")

#cmdenv-output-file=input/washingtondc/seed-${seedset}/${Nv}/results/transient-cache/washingtondc-${seedset}-${Nv}.out
cmdenv-output-file = ./results/seed-${seedset}/output//${Nv}.out
##########################################################
#                       RSU SETTINGS                     #
#                                                        #
#                                                        #
##########################################################
*.rsu[0].mobility.x = 2246.59
*.rsu[0].mobility.y = 2038.29
*.rsu[0].mobility.z = 4


#*.rsu[1].mobility.x = 2246.59
#*.rsu[1].mobility.y = 2038.29
#*.rsu[1].mobility.z = 1
*.rsu[1].mobility.x = 2280.59
*.rsu[1].mobility.y = 860.29
*.rsu[1].mobility.z = 1

*.rsu[2].mobility.x = 1755.54
*.rsu[2].mobility.y = 1241.46
*.rsu[2].mobility.z = 1

*.rsu[3].mobility.x = 1062.01
*.rsu[3].mobility.y = 1064.18
*.rsu[3].mobility.z = 1

*.rsu[4].mobility.x = 1721.38
*.rsu[4].mobility.y = 1681.26
*.rsu[4].mobility.z = 1

*.rsu[5].mobility.x = 1162.01
*.rsu[5].mobility.y = 1285.53
*.rsu[5].mobility.z = 1

*.rsu[6].mobility.x = 1349.89
*.rsu[6].mobility.y = 1537.46
*.rsu[6].mobility.z = 1

*.rsu[7].mobility.x = 2016.01
*.rsu[7].mobility.y = 1232.92
*.rsu[7].mobility.z = 1

*.rsu[8].mobility.x = 1332.81
*.rsu[8].mobility.y = 1183.06
*.rsu[8].mobility.z = 1

*.rsu[9].mobility.x = 824.68
*.rsu[9].mobility.y = 939.67
*.rsu[9].mobility.z = 1

*.rsu[10].mobility.x = 730.74
#*.rsu[10].mobility.y = 1281.26
*.rsu[10].mobility.y = 2038.29

*.rsu[10].mobility.z = 1

*.rsu[11].mobility.x = 581.29
*.rsu[11].mobility.y = 969.56
*.rsu[11].mobility.z = 1

#*.rsu[*].mobility.x = uniform(500, 2500)
#*.rsu[*].mobility.y = uniform(0, 2000)
#*.rsu[*].mobility.z = uniform(1, 10)

*.rsu[*].applType = "TraCIDemoRSU11p"
*.rsu[*].appl.headerLength = 80 bit
*.rsu[*].appl.sendBeacons = false
*.rsu[*].appl.dataOnSch = false
*.rsu[*].appl.beaconInterval = 5s
*.rsu[*].appl.beaconUserPriority = 7
*.rsu[*].appl.dataUserPriority = 5
*.rsu[*].nic.phy80211p.antennaOffsetZ = 0 m

*.rsu[0].appl.RSU_stats_DataFileName = "/home/nadia/Brock/Thesis/SDVN/simulations/veins/results/${configname}/rsu/seed${seedset}/rsu0_stats_${configname}_Nv=${Nv}.csv"
*.rsu[1].appl.RSU_stats_DataFileName = "/home/nadia/Brock/Thesis/SDVN/simulations/veins/results/${configname}/rsu/seed${seedset}/rsu1_stats_${configname}_Nv=${Nv}.csv"
*.rsu[2].appl.RSU_stats_DataFileName = "/home/nadia/Brock/Thesis/SDVN/simulations/veins/results/${configname}/rsu/seed${seedset}/rsu2_stats_${configname}_Nv=${Nv}.csv"
*.rsu[3].appl.RSU_stats_DataFileName = "/home/nadia/Brock/Thesis/SDVN/simulations/veins/results/${configname}/rsu/seed${seedset}/rsu3_stats_${configname}_Nv=${Nv}.csv"

*.rsu[4].appl.RSU_stats_DataFileName = "/home/nadia/Brock/Thesis/SDVN/simulations/veins/results/${configname}/rsu/seed${seedset}/rsu4_stats_${configname}_Nv=${Nv}.csv"
*.rsu[5].appl.RSU_stats_DataFileName = "/home/nadia/Brock/Thesis/SDVN/simulations/veins/results/${configname}/rsu/seed${seedset}/rsu5_stats_${configname}_Nv=${Nv}.csv"
*.rsu[6].appl.RSU_stats_DataFileName = "/home/nadia/Brock/Thesis/SDVN/simulations/veins/results/${configname}/rsu/seed${seedset}/rsu6_stats_${configname}_Nv=${Nv}.csv"
*.rsu[7].appl.RSU_stats_DataFileName = "/home/nadia/Brock/Thesis/SDVN/simulations/veins/results/${configname}/rsu/seed${seedset}/rsu7_stats_${configname}_Nv=${Nv}.csv"

*.rsu[8].appl.RSU_stats_DataFileName = "/home/nadia/Brock/Thesis/SDVN/simulations/veins/results/${configname}/rsu/seed${seedset}/rsu8_stats_${configname}_Nv=${Nv}.csv"
*.rsu[9].appl.RSU_stats_DataFileName = "/home/nadia/Brock/Thesis/SDVN/simulations/veins/results/${configname}/rsu/seed${seedset}/rsu9_stats_${configname}_Nv=${Nv}.csv"
*.rsu[10].appl.RSU_stats_DataFileName = "/home/nadia/Brock/Thesis/SDVN/simulations/veins/results/${configname}/rsu/seed${seedset}/rsu10_stats_${configname}_Nv=${Nv}.csv"
#*.rsu[10].appl.RSU_stats_DataFileName = "/home/nadia/Brock/Thesis/SDVN/simulations/veins/results/${configname}/rsu/seed${seedset}/rsu10/rsu10_stats_${configname}_Nv=${Nv}.csv"
*.rsu[11].appl.RSU_stats_DataFileName = "/home/nadia/Brock/Thesis/SDVN/simulations/veins/results/${configname}/rsu/seed${seedset}/rsu11_stats_${configname}_Nv=${Nv}.csv"


#*.rsu[*].appl.connectToTraCI = false
#*.rsu[*].numRadios = 1

# RSU INET Network Stack Configuration
# Ensure these match the typenames in RSU.ned

*.rsu[*].appl.controllerPort = 6653 # Standard OpenFlow port, can be changed

*.**.networkLayer.arp.typename = "GlobalArp"


# Configure IP for wlan interfaces of RSUs if they act as IP routers on wireless.
# For simplicity, if only WSMs are sent, IP on wlan might not be strictly needed.
# If you add IP to wlan, ensure it's on a different subnet from the wired one.
# Example: *.rsu[0].nic.networkLayer.ipv4.interfaceTable.wlan0.address = "192.168.1.10"
# *.rsu[0].nic.networkLayer.ipv4.interfaceTable.wlan0.netmask = "255.255.255.0"




##########################################################
#                       OFS SETTINGS                     #
#                                                        #
#                                                        #
##########################################################

# Open_Flow_Switch network layer configuration (internal modules)
# The switch also needs its own IP stack to communicate with RSUs and controller
*.open_flow_switch*.networkLayer.typename = "IPv4NetworkLayer"
*.open_flow_switch*.routingTable.typename = "IPv4RoutingTable"
*.open_flow_switch*.interfaceTable.typename = "InterfaceTable"
*.open_flow_switch*.tcpType = "TCP" # Can be "UDP" if preferred for OF communication

#openflow params
**.open_flow_switch1.OF_Switch.connectAddress = "open_flow_controller1"
**.open_flow_switch2.OF_Switch.connectAddress = "open_flow_controller2"
**.open_flow_switch3.OF_Switch.connectAddress = "open_flow_controller3"
**.open_flow_switch4.OF_Switch.connectAddress = "open_flow_controller4"

**.open_flow_switch*.OF_Switch.connectAt = 0s
**.open_flow_switch*.etherMAC[*].promiscuous = true


# --- Controller Application Configuration ---
*.open_flow_controller1.numControllerApps = 2

*.open_flow_controller1.controllerApps[0].typename = "ARPResponder"
*.open_flow_controller1.controllerApps[0].arp_cache = xml("<config><entry ip='10.0.0.13' mac='0A-AA-00-00-00-10'/><entry ip='10.0.0.17' mac='0A-AA-00-00-00-11'/><entry ip='10.0.0.21' mac='0A-AA-00-00-00-12'/></config>")
*.open_flow_controller1.controllerApps[1].typename = "LoggingApp"
*.open_flow_controller1.controllerApps[1].vehicleDataFileName = "/home/nadia/Brock/Thesis/SDVN/simulations/veins/results/${configname}/seed${seedset}/vehicle_log_district_1_${configname}_Nv=${Nv}.csv"
*.open_flow_controller1.controllerApps[1].districtID = 0
*.open_flow_controller1.controllerApps[1].inferLocalInterval = 9.9s


*.open_flow_controller2.numControllerApps = 2

*.open_flow_controller2.controllerApps[0].typename = "ARPResponder"
*.open_flow_controller2.controllerApps[0].arp_cache = xml("<config><entry ip='10.0.0.25' mac='0A-AA-00-00-00-14'/><entry ip='10.0.0.29' mac='0A-AA-00-00-00-15'/><entry ip='10.0.0.33' mac='0A-AA-00-00-00-16'/></config>")
*.open_flow_controller2.controllerApps[1].typename = "LoggingApp"
*.open_flow_controller2.controllerApps[1].vehicleDataFileName = "/home/nadia/Brock/Thesis/SDVN/simulations/veins/results/${configname}/seed${seedset}/vehicle_log_district_2_${configname}_Nv=${Nv}.csv"
*.open_flow_controller2.controllerApps[1].districtID = 1
*.open_flow_controller2.controllerApps[1].inferLocalInterval = 9.9s


*.open_flow_controller3.numControllerApps = 2

*.open_flow_controller3.controllerApps[0].typename = "ARPResponder"
*.open_flow_controller3.controllerApps[0].arp_cache = xml("<config><entry ip='10.0.0.37' mac='0A-AA-00-00-00-18'/><entry ip='10.0.0.41' mac='0A-AA-00-00-00-19'/><entry ip='10.0.0.45' mac='0A-AA-00-00-00-1A'/></config>")
*.open_flow_controller3.controllerApps[1].typename = "LoggingApp"
*.open_flow_controller3.controllerApps[1].vehicleDataFileName = "/home/nadia/Brock/Thesis/SDVN/simulations/veins/results/${configname}/seed${seedset}/vehicle_log_district_3_${configname}_Nv=${Nv}.csv"
*.open_flow_controller3.controllerApps[1].districtID = 2
*.open_flow_controller3.controllerApps[1].inferLocalInterval = 9.9s


*.open_flow_controller4.numControllerApps = 2

*.open_flow_controller4.controllerApps[0].typename = "ARPResponder"
*.open_flow_controller4.controllerApps[0].arp_cache = xml("<config><entry ip='10.0.0.49' mac='0A-AA-00-00-00-1C'/><entry ip='10.0.0.53' mac='0A-AA-00-00-00-1D'/><entry ip='10.0.0.57' mac='0A-AA-00-00-00-1E'/></config>")
*.open_flow_controller4.controllerApps[1].typename = "LoggingApp"
*.open_flow_controller4.controllerApps[1].vehicleDataFileName = "/home/nadia/Brock/Thesis/SDVN/simulations/veins/results/${configname}/seed${seedset}/vehicle_log_district_4_${configname}_Nv=${Nv}.csv"
*.open_flow_controller4.controllerApps[1].districtID = 3
*.open_flow_controller4.controllerApps[1].inferLocalInterval = 9.9s

*.open_flow_controller_main.numControllerApps = 1
*.open_flow_controller_main.controllerApps[0].typename = "GnnModel"
*.open_flow_controller_main.controllerApps[0].glob = "/home/nadia/Brock/Thesis/SDVN/simulations/veins/results/${configname}/seed${seedset}/*.csv"
*.open_flow_controller_main.controllerApps[0].mergeScript = "/home/nadia/Brock/Thesis/openflow4core-20240124/model/merge_logs.py"

*.open_flow_controller_main.controllerApps[0].inferInterval = 10s
*.open_flow_controller_main.controllerApps[0].pyExec = "/home/nadia/Brock/Thesis/omnetpp-6.0.3/.venv/bin/python3"
*.open_flow_controller_main.controllerApps[0].inferScript = "/home/nadia/Brock/Thesis/openflow4core-20240124/model/infer_once.py"
*.open_flow_controller_main.controllerApps[0].modelPath = "/home/nadia/Brock/Thesis/openflow4core-20240124/model/stgnn.pth"
*.open_flow_controller_main.controllerApps[0].mergedCsv = "/home/nadia/Brock/Thesis/openflow4core-20240124/model/mergedCsv.csv"
*.open_flow_controller_main.controllerApps[0].rsuPositions = "/home/nadia/Brock/Thesis/openflow4core-20240124/model/rsu_positions.json"
*.open_flow_controller_main.controllerApps[0].outDecisions = "/home/nadia/Brock/Thesis/openflow4core-20240124/model/decisions_${configname}_seed${seedset}_Nv=${Nv}.csv"
*.open_flow_controller_main.controllerApps[0].inference_outputs = "/home/nadia/Brock/Thesis/openflow4core-20240124/model/inference_outputs_${configname}_seed${seedset}_Nv=${Nv}.csv"
*.open_flow_controller_main.controllerApps[0].inference_overhead =  "/home/nadia/Brock/Thesis/openflow4core-20240124/model/inference_overhead_${configname}_seed${seedset}_Nv=${Nv}.csv"
*.open_flow_controller_main.controllerApps[0].files1 = "/home/nadia/Brock/Thesis/SDVN/simulations/veins/results/${configname}/seed${seedset}/vehicle_log_district_1_${configname}_Nv=${Nv}.csv"
*.open_flow_controller_main.controllerApps[0].files2 = "/home/nadia/Brock/Thesis/SDVN/simulations/veins/results/${configname}/seed${seedset}/vehicle_log_district_2_${configname}_Nv=${Nv}.csv"
*.open_flow_controller_main.controllerApps[0].files3 = "/home/nadia/Brock/Thesis/SDVN/simulations/veins/results/${configname}/seed${seedset}/vehicle_log_district_3_${configname}_Nv=${Nv}.csv"
*.open_flow_controller_main.controllerApps[0].files4 = "/home/nadia/Brock/Thesis/SDVN/simulations/veins/results/${configname}/seed${seedset}/vehicle_log_district_4_${configname}_Nv=${Nv}.csv"
*.open_flow_controller_main.controllerApps[0].controller_overhead = "/home/nadia/Brock/Thesis/openflow4core-20240124/model/controller_overhead_${configname}_seed${seedset}_Nv=${Nv}.csv"
# 404bytes see imix and buffer size of 1.5mb see hp switch 1500000/404
**.OF_Switch.bufferCapacity = 3712
*.open_flow_switch*.sendCompletePacket = true


**.OF_Switch.serviceTime = 0.000035s * (${switchServiceTimeFactor= 1,130,140,150,152,154,156,158,160,170,180,190,200})

##########################################################
#                  NETWORK CONFIGURATION                 #
##########################################################
**.configurator.typename = "inet::IPv4NetworkConfigurator"
**.configurator.assignAddresses = true
**.configurator.assignDisjunctSubnetAddresses = true
**.configurator.addDefaultRoutes = true

# This ensures all nodes can forward packets if needed
*.**.routingTable.forwarding = true
#*.rsu[*].networkLayer.igmpPresent = false


################################################ ##########
#            11p specific parameters                     #
#                                                        #
#                    NIC-Settings                        #
##########################################################
*.connectionManager.sendDirect = true
*.connectionManager.maxInterfDist = 300m #2600m
*.connectionManager.drawMaxIntfDist = false

*.**.nic.mac1609_4.useServiceChannel = false

*.**.nic.mac1609_4.txPower = 20mW
*.**.nic.mac1609_4.bitrate = 6Mbps
*.**.nic.phy80211p.minPowerLevel = -110dBm

*.**.nic.phy80211p.useNoiseFloor = true
*.**.nic.phy80211p.noiseFloor = -98dBm

*.**.nic.phy80211p.decider = xmldoc("config.xml")
*.**.nic.phy80211p.analogueModels = xmldoc("config.xml")
*.**.nic.phy80211p.usePropagationDelay = true

*.**.nic.phy80211p.antenna = xmldoc("antenna.xml", "/root/Antenna[@id='monopole']")
*.node[*].nic.phy80211p.antennaOffsetY = 0 m
*.node[*].nic.phy80211p.antennaOffsetZ = 1.895 m

##########################################################
#                      App Layer                         #
##########################################################
*.node[*].applType = "TraCIDemo11p"
*.node[*].appl.headerLength = 80 bit
*.node[*].appl.sendBeacons = false
*.node[*].appl.dataOnSch = false
*.node[*].appl.beaconInterval = 2s

##########################################################
#                      Mobility                          #
##########################################################
*.node[*].veinsmobility.x = 0
*.node[*].veinsmobility.y = 0
*.node[*].veinsmobility.z = 0
*.node[*].veinsmobility.setHostSpeed = false
#*.node[*0].veinsmobility.accidentCount = 0
#*.node[*0].veinsmobility.accidentStart = 73s
#*.node[*0].veinsmobility.accidentDuration = 50s

#${alphaZ=0.25,0.40,0.60,0.80,1}
**.appl.alphaZ = ${alphaZ=0.25}

[Config Default]


[Config WithBeaconing]
*.rsu[*].appl.sendBeacons = true
*.node[*].appl.sendBeacons = true
#*.node[*].appl.beaconInterval = 3s
#*.rsu[*].networkLayer.arp.cacheTimeout = 300s

[Config WithChannelSwitching]
*.**.nic.mac1609_4.useServiceChannel = true
*.node[*].appl.dataOnSch = true
*.rsu[*].appl.dataOnSch = true

[Config TestMobility]

# Create only ONE RSU and ZERO other nodes
*.rsu.numModules = 1
*.node[*].numModules = 0
*.open_flow_switch1.numModules = 0
*.open_flow_controller1.numModules = 0
*.etherSwitch.numModules = 0

# Apply our application and mobility settings ONLY to this one RSU
*.rsu[0].applType = "TraCIDemoRSU11p"
*.rsu[0].mobility.initialX = 1780.43m
*.rsu[0].mobility.initialY = 2150.95m
*.rsu[0].mobility.initialZ = 4m

*.rsu[1].mobility.initialX = 2246.59m
*.rsu[1].mobility.initialY = 2038.29m
*.rsu[1].mobility.initialZ = 1m
######################################



