//
// Generated file, do not edit! Created by opp_msgtool 6.0 from inet/controller_messages/ControllerCommand.msg.
//

#ifndef __INET_CONTROLLERCOMMAND_M_H
#define __INET_CONTROLLERCOMMAND_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif


namespace inet {

class ControllerCommand;

}  // namespace inet


namespace inet {

/**
 * Class generated from <tt>inet/controller_messages/ControllerCommand.msg:21</tt> by opp_msgtool.
 * <pre>
 * packet ControllerCommand
 * {
 *     string cmd;             // "attach", "reroute"
 *     string targetRSU;       // target RSU for attach/reroute
 *     int vehicleIDs[];       // list of vehicles
 * }
 * </pre>
 */
class INET_API ControllerCommand : public ::omnetpp::cPacket
{
  protected:
    ::omnetpp::opp_string cmd;
    ::omnetpp::opp_string targetRSU;
    int *vehicleIDs = nullptr;
    size_t vehicleIDs_arraysize = 0;

  private:
    void copy(const ControllerCommand& other);

  protected:
    bool operator==(const ControllerCommand&) = delete;

  public:
    ControllerCommand(const char *name=nullptr, short kind=0);
    ControllerCommand(const ControllerCommand& other);
    virtual ~ControllerCommand();
    ControllerCommand& operator=(const ControllerCommand& other);
    virtual ControllerCommand *dup() const override {return new ControllerCommand(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getCmd() const;
    virtual void setCmd(const char * cmd);

    virtual const char * getTargetRSU() const;
    virtual void setTargetRSU(const char * targetRSU);

    virtual void setVehicleIDsArraySize(size_t size);
    virtual size_t getVehicleIDsArraySize() const;
    virtual int getVehicleIDs(size_t k) const;
    virtual void setVehicleIDs(size_t k, int vehicleIDs);
    virtual void insertVehicleIDs(size_t k, int vehicleIDs);
    [[deprecated]] void insertVehicleIDs(int vehicleIDs) {appendVehicleIDs(vehicleIDs);}
    virtual void appendVehicleIDs(int vehicleIDs);
    virtual void eraseVehicleIDs(size_t k);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ControllerCommand& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ControllerCommand& obj) {obj.parsimUnpack(b);}


}  // namespace inet


namespace omnetpp {

template<> inline inet::ControllerCommand *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::ControllerCommand*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __INET_CONTROLLERCOMMAND_M_H

