//
// Generated file, do not edit! Created by opp_msgtool 6.0 from openflow/messages/ControllerPacket.msg.
//

#ifndef __CONTROLLERPACKET_M_H
#define __CONTROLLERPACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class ControllerPacket;
/**
 * Class generated from <tt>openflow/messages/ControllerPacket.msg:19</tt> by opp_msgtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet ControllerPacket
 * {
 *     cPacket *originalVehicleMessage; // Encapsulates the TraCIDemo11pMessage or BaseFrame1609_4
 *     string rsuId;                    // Full path of the RSU that sent the packet
 *     string sourceVehicleId;          // ID/Address of the original sending vehicle
 *     string destinationVehicleId;     // ID/Address of the target vehicle
 *     string controllerInstruction;    // e.g., "FORWARD_TO_RSU", "DROP", "LOCAL_DELIVER"
 *     string targetRsuId;              // Which RSU should forward this packet (if controller decided)
 * }
 * </pre>
 */
class ControllerPacket : public ::omnetpp::cPacket
{
  protected:
    omnetpp::cPacket * originalVehicleMessage = nullptr;
    omnetpp::opp_string rsuId;
    omnetpp::opp_string sourceVehicleId;
    omnetpp::opp_string destinationVehicleId;
    omnetpp::opp_string controllerInstruction;
    omnetpp::opp_string targetRsuId;

  private:
    void copy(const ControllerPacket& other);

  protected:
    bool operator==(const ControllerPacket&) = delete;

  public:
    ControllerPacket(const char *name=nullptr, short kind=0);
    ControllerPacket(const ControllerPacket& other);
    virtual ~ControllerPacket();
    ControllerPacket& operator=(const ControllerPacket& other);
    virtual ControllerPacket *dup() const override {return new ControllerPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const omnetpp::cPacket * getOriginalVehicleMessage() const;
    virtual omnetpp::cPacket * getOriginalVehicleMessageForUpdate() { return const_cast<omnetpp::cPacket *>(const_cast<ControllerPacket*>(this)->getOriginalVehicleMessage());}
    virtual void setOriginalVehicleMessage(omnetpp::cPacket * originalVehicleMessage);

    virtual const char * getRsuId() const;
    virtual void setRsuId(const char * rsuId);

    virtual const char * getSourceVehicleId() const;
    virtual void setSourceVehicleId(const char * sourceVehicleId);

    virtual const char * getDestinationVehicleId() const;
    virtual void setDestinationVehicleId(const char * destinationVehicleId);

    virtual const char * getControllerInstruction() const;
    virtual void setControllerInstruction(const char * controllerInstruction);

    virtual const char * getTargetRsuId() const;
    virtual void setTargetRsuId(const char * targetRsuId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ControllerPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ControllerPacket& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline ControllerPacket *fromAnyPtr(any_ptr ptr) { return check_and_cast<ControllerPacket*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __CONTROLLERPACKET_M_H

